### ISSUE TITLE
ACLPUB ownership?

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-pub#13]
Is there a clear owner of this repo? There are a number of open PRs and Issues that haven't seen any activity, and it seems there should be some benevolent dictator in charge of it, given its centrality to the *ACL publication process.

I can see this falling under the purview of the Anthology or ACL directory.

Also, can anyone shed light on the following repos?

- https://github.com/aclpub/aclpub
- https://github.com/acl-org/archive

I think it would be helpful to clear these out to reduce confusion.

Finally, I also think it's unusual that the main branch here is "gh-pages". This is one mechanism on Github for the repo to double as a web page, but since web documentation is only a secondary purpose of this repo, I would suggest a more natural way to accomplish this might be [under the `docs/` folder](https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages) on the master branch.

(Tagging people who've been pushing lately: @desilinguist @danielgildea @davidweichiang @slukin)

**Comment by desilinguist** [comment]
I think it makes sense for this to fall under the Anthology.

**Comment by davidweichiang** [comment]
Does ACLPUB have any other outputs other than the Anthology now? If not, I’d definitely say it should be owned by the Anthology or even merged into it.

**Comment by mjpost** [comment]
There are other targets, such as the conference webpage, the online schedule, the handbook, and the digital handbook. But these all make use of a structure designed for the Anthology, and that's the long-term recipient.

Does anyone know, is this the actual ACLPUB repo? It seems there is a dual use as an information page used by the current pub chairs (and in fact, this repo is forked [from one that Colin and I created in 2013](https://github.com/naacl-org/naacl-pubs)). It seems a bit odd for me that the authoritative ACLPUB scripts should be buried where they are under [assets/files/](https://github.com/acl-org/acl-pub/tree/gh-pages/assets/files).

**Comment by mmitchellai** [comment]
Heya,
It's the "actual" ACLPUB repo, but does need a real owner.
Please feel free to move things around and re-organize.
We started this over the course of a couple *ACLs, but needs some more
dedicated time.

**Comment by mjpost** [comment]
Okay, great to have this confirmed. Do you remember where it came from?

Thanks for helping set this up!

**Comment by mmitchellai** [comment]
Yeah, it was an effort to unify the style formats across NAACL and ACL as
well as being a place where there is a HOW TO, where ACL members could
contribute, and where softconf could pull from information.  It unified the
previous NAACL pub GitHub repository and other floating ACL files.

**Comment by mmitchellai** [comment]
I tried to get some other proceedings chairs engaged to take it on, but
mixed results. It definitely needs some TLC.
Also, if it's going to work as a group repo, should be made more
clear/announced within ACL community.

Thanks so much for working on this!

**Comment by davidweichiang** [comment]
I've just learned that Softconf maintains its own version of ACLPUB, which is the one that program/pub chairs are actually using.

**Comment by mmitchellai** [comment]
Good to separate between the style files and the softconf scripts.  I've
tried to ask the softconf folks to share the softconf scripts via the
ACLPUB GitHub repo, but they haven't been able to.

**Comment by mmitchellai** [comment]
Ah!  Sorry, I misunderstood what this was referring to (I didn't click on
the links).
Disregard!

**Comment by davidweichiang** [comment]
No, I think your comment is helpful. I hope we can find a good arrangement with Softconf. It seems to me that there are really four main pieces in this repo:

1. Instructions for book and publication chairs (which seems to have been the original purpose of the repo).

2. Style files and their accompanying instructions for authors.

3. The part of ACLPUB that now runs on START. There are currently two diverging versions of this piece, one maintained by Softconf and the one here. 
- I found the version that Softconf used for EMNLP 2018. It looks like they have made many improvements parallel to the ones that have been made here, and more. But there are still bugs that are affecting the downstream XML.
- The current instructions do mention an [expert route](https://github.com/acl-org/acl-pub/blob/gh-pages/002.book.md#expert-route) that involves using the version in this repo.

4. The part of ACLPUB that is run by conference pub chairs.
- download-proceedings.sh, make_anthology.sh, and anthologize.pl
- anthologize.pl works strictly from the .bib and .pdf files and attachments.

**Comment by mjpost** [comment]
This is a succinct and thorough summary of the state of things, I think.

Offline, we are working with Softconf to resolve the discrepancies. I hope we can pull out (3) and make our own repo, i.e., http://github.com/acl-org/ACLPUB.

Can you link to the EMNLP 2018 ACLPUB? Is it a git repo?

**Comment by davidweichiang** [comment]
Softconf's ACLPUB is included in the tarball when you finally export everything. So I was able to access the one for EMNLP 2018. I'm unsure whether I can share it given that it's been modified by Softconf. Let's wait to see what they say about a common repo (which would be ideal)?

**Comment by mjpost** [comment]
Sounds good.

**Comment by mjpost** [comment]
Okay, Softconf has provided their version, which I've cloned here: https://github.com/acl-org/ACLPUB. I will probably not look at this more deeply until Tuesday.

**Comment by mjpost** [comment]
I'm marking this as resolved. Feel free to reopen if there is more on-topic discussion needed.

**Comment by davidweichiang** [comment]
Also, I don't think we resolved the question of where anthologize.pl should go.

Reasons to keep it here:
- It is run by pub chairs on their local machine, so it should stay here with the rest of the pub chair stuff.
- Modifications to anthologize.pl don't concern Softconf, so we don't want to distract them.

Reasons to move it to ACLPUB:
- It logically belongs to the pipeline leading from START to the Anthology, so it should stay with the rest of the pipeline.
- It may share code with ACLPUB, but I'm hoping that that sharing can be eliminated. (At least for now.)

**Comment by danielgildea** [comment]
I think it's simpler to have everything in one repository.  The scripts 
interact with each other even when they are not run on the same machine.
So I would support merging our recent changes to anthologize.pl into the new
ACLPUB repository.

**Comment by slukin** [comment]
Hi all, I'm just getting caught up with this thread.

I can see an argument for keeping the acl-pub repo for everything but code,
basically with the paper templates, files, and instructions for authors and
book chairs. Then the ACLPUB repo would have both the START and proceedings
generation code.

If this is the proposed way forward, I think the main documentation to copy
into ACLPUB is this file [
https://github.com/acl-org/acl-pub/blob/gh-pages/full-aclweb-proceedings-howto.md]
that accompanies the make_anthology.sh proceedings generation scripts.

Stephanie

**Comment by mjpost** [comment]
I think we should leave `anthologize.pl` here regardless, and expect that pub chairs will have to clone this repo.

I like the idea of keeping it all together, but I am worried about having too many cooks working on this single repo, moving things around and changing things, and often with an (understandable) goal to just get their immediate job done and not worry too much about the longer term (just to be clear, I exclude you from this group, @slukin). And this might get exacerbated if different overlapping conferences are trying different things—inevitably, there will be multiple branches or forks (#17), and I think it would be clearer if ACLPUB were not part of that forking madness. The goal with [ACLPUB](https://github.com/acl-org/ACLPUB) is to have a single, obvious, non-forked, authoritative source for data getting fed into the Anthology.

This view would argue for keeping `anthologize.pl` here and possibly also [make_anthology.sh](https://github.com/acl-org/acl-pub/blob/gh-pages/assets/files/aclweb_proceedings/make_anthology.sh), but keeping things like style files and per-conference chair-focused information in some descendant of [acl-pub](https://github.com/acl-org/acl-pub).

I think the distinction I'm arguing for is: 

- stable, Anthology-focused stuff under ACLPUB
- ephemeral, conference-specific stuff under acl-pub or whatever

**Comment by mmitchellai** [comment]
Thanks for taking this on guys, this is looking really good.

**Comment by davidweichiang** [comment]
@mjpost By "here" which repository did you mean? From the context it wasn't clear.

**Comment by mjpost** [comment]
Whoops. I mean in ACLUB—I just corrected everything above.

**Comment by davidweichiang** [comment]
OK, so at some point everything in create_book as well as in aclweb_proceedings will move over to ACLPUB. I'll take a look at merging our changes to anthologize.pl into ACLPUB.

**Comment by mjpost** [comment]
I think this is completed now.
