### ISSUE TITLE
Use a different branch/fork for each conference?

### ISSUE THREAD

**Issue by davidweichiang** [acl-org/acl-pub#17]
Many of the documents in this repository are tailored for specific conferences. But we often have multiple overlapping review cycles (e.g., NAACL is in camera ready now and ACL is taking submissions). Would it be better to use a different branch for each conference? Or different subdirectories?

**Comment by logological** [comment]
Different branches would probably be better than different subdirectories.  Otherwise each time a common bug is found, or a common feature introduced, it'd be have to be applied separately to the style for every conference.

**Comment by davidweichiang** [comment]
I agree; see #22 at the moment, where we're trying to merge improvements made by ACL 2020 with improvements made independently in this repo.

**Comment by davidweichiang** [comment]
Here's what I propose to make this more maintainable.

1. This repository should not belong to any single conference/year; it should be generic for any *ACL meeting. To that end:
- It should be maintained by a small number of people, not all publications chairs. I don't know who that set of people should be.
- There should be one and only one LaTeX style file, Word style file, etc., not one for each conference. The `back` and `archive` subdirectories should be deleted.
- Filenames should be generic. Filenames that include the conference name should be renamed in here to `aclbase.sty`, `aclbase.docx`, etc., but if someone has a better name please say so.

2. Individual conference publications chairs can fork this repository and customize it however they like. In particular, they'd rename `aclbase.sty` to `acl2021.sty`, etc.

3. The instructions should urge publications chairs to submit PRs for the changes they make that should be passed on to future conferences.

**Comment by davidweichiang** [comment]
I'm not sure who to get an ok from on this... @mjpost? @desilinguist?

**Comment by mjpost** [comment]
I think you or @dangildea are the closest thing to an owner that this repo has.

It would be good to have a formal owner here...

**Comment by mjpost** [comment]
I like your suggestions above. I also thing this repo should be renamed (`acl-style`?) and that it should use the `master` branch. 

It should also be cleaned up. Are the style files all that is used here anymore? Or is the documentation also somehow authoritative. I believe this is a clone of the `naacl-pub` repo that Colin and I created in 2013 to hold pubchair information, but this doesn't seem the ideal place for that, I don't think.

**Comment by davidweichiang** [comment]
I think even the style files here are not always used. I'm not sure whether the instructions are used.
