### ISSUE TITLE
acl_natbib.bst sometimes misses extra labels on years

### ISSUE THREAD

**Issue by bhaddow** [acl-org/acl-pub#25]
Hi 

I have two bibliography entries for the same year, with the same lead author, but different author lists. the ACL2020 latex style does not add the extra label to the year, so both entries appear the same in the text. In other words, they both appear as (Haddow et al, 2020) instead of (Haddow et al, 2020a) and (Haddow et al, 2020b). In the case where the author list and the year both match, the extra label is added correctly. 

This appears to be the same as, or similar to, this problem https://tex.stackexchange.com/questions/416723/jneurosci-bibliography-style-missing-extra-labels-a-b-for-year-field-fo . The suggested hack (editing the bbl) solves the problem, but is only a short-term fix for the workshop deadline,

all the best
Barry

**Comment by mjpost** [comment]
@danielgildea, do you know how to fix this?

**Comment by danielgildea** [comment]
Hi,

The example from stackexchange works for me.  Can you send a 
minimal bibtex file and latex file?

**Comment by bhaddow** [comment]
This example fails https://www.overleaf.com/9869673223yyddmxpjtxrx

However, I see what the problem is now. In one of the references in the bib file, the first author has curly brackets around their surname. I assume that's why bibtex things they are different authors, even though they display the same.

**Comment by danielgildea** [comment]
Ah, I see.  I don't think we can do anything about that.
