### ISSUE TITLE
"patch failed" error

### ISSUE THREAD

**Issue by davidweichiang** [acl-org/acl-pub#28]
https://tex.stackexchange.com/questions/487428/patch-failed-in-emnlp-style-template

**Comment by danielgildea** [comment]
This bug isn't present in the version in our github repo:

https://github.com/acl-org/acl-pub/pull/22

Unfortunately, the pub chairs are generally not aware that this repo exists,
and so they just copy style files from last year's conference website.

**Comment by davidweichiang** [comment]
Oops, thanks
