### ISSUE TITLE
“Patch failed” in EMNLP Style Template

### ISSUE THREAD

**Issue by drevicko** [acl-org/acl-pub#32]
See [this Tex SO page](https://tex.stackexchange.com/questions/487428/patch-failed-in-emnlp-style-template).

[David Carliles' suggestion](https://tex.stackexchange.com/questions/487428/patch-failed-in-emnlp-style-template/487751?noredirect=1#comment1386003_487751):

> if they change \errmessage to \wlog it will just log that the patch failed in new releases, but still do the patch in old releases and will work the same way in either case. – David Carlisle Jun 10 at 7:52

**Comment by danielgildea** [comment]
This bug is not present in the version of the style files in this repository.

https://github.com/acl-org/acl-pub/pull/22#issuecomment-553903712

**Comment by drevicko** [comment]
Just a heads up that the bug appeared to be present in EMNLP 2020 style files as downloaded from the official website not so long ago. 

Apologies I didn't find that this had already been reported (I believe I did search, though maybe presumed it hadn't been reported since it appeared in EMNLP 2020?).
